"""Allowlisted tool definitions and conversion schemas for LLMs.

Enforces Rule R5: LLMs are strictly bounded to this fixed tool allowlist.
Any function call generated by Gemini, Agnes, or Ollama is validated through
AllowlistValidator before returning an ActionRequest.
"""

from __future__ import annotations

import logging
from typing import Any

from nova.core.actions import ActionID, AllowlistValidator
from nova.core.interfaces import ActionRequest

logger = logging.getLogger(__name__)

# Canonical tool schemas in OpenAI / JSON schema format
NOVA_TOOLS_SCHEMA: list[dict[str, Any]] = [
    {
        "type": "function",
        "function": {
            "name": "volume_set",
            "description": "Set master system volume to a specific percentage (0 to 100).",
            "parameters": {
                "type": "object",
                "properties": {
                    "percent": {
                        "type": "integer",
                        "description": "Target volume percentage from 0 to 100.",
                        "minimum": 0,
                        "maximum": 100,
                    }
                },
                "required": ["percent"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "volume_change",
            "description": "Increase or decrease system volume.",
            "parameters": {
                "type": "object",
                "properties": {
                    "direction": {
                        "type": "string",
                        "enum": ["up", "down"],
                        "description": "Direction to change volume: 'up' or 'down'.",
                    }
                },
                "required": ["direction"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "volume_mute_toggle",
            "description": "Toggle system audio mute on or off.",
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "media_control",
            "description": "Control system media playback.",
            "parameters": {
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "enum": ["play_pause", "next", "previous", "stop"],
                        "description": "Media command: 'play_pause', 'next', 'previous', or 'stop'.",
                    }
                },
                "required": ["action"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "app_launch",
            "description": "Launch an application or software by name (e.g. 'Brave', 'Chrome', 'Spotify', 'Notepad').",
            "parameters": {
                "type": "object",
                "properties": {
                    "app_name": {
                        "type": "string",
                        "description": "Name of the application to launch.",
                    }
                },
                "required": ["app_name"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "app_close",
            "description": "Close a running application by name.",
            "parameters": {
                "type": "object",
                "properties": {
                    "app_name": {
                        "type": "string",
                        "description": "Name of the application to close.",
                    }
                },
                "required": ["app_name"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "system_lock",
            "description": "Lock the workstation or desktop user session.",
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "system_sleep",
            "description": "Put the computer into suspend or sleep mode.",
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "dark_mode_toggle",
            "description": "Toggle between OS dark and light display modes.",
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "web_search",
            "description": "Search the web using Google.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Search query terms.",
                    }
                },
                "required": ["query"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "web_open_url",
            "description": "Open a specific web address or website URL in default browser.",
            "parameters": {
                "type": "object",
                "properties": {
                    "url": {
                        "type": "string",
                        "description": "Complete HTTP or HTTPS URL to open.",
                    }
                },
                "required": ["url"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "timer_set",
            "description": "Set a countdown timer for a specified number of seconds.",
            "parameters": {
                "type": "object",
                "properties": {
                    "duration_seconds": {
                        "type": "number",
                        "description": "Duration in seconds.",
                    }
                },
                "required": ["duration_seconds"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "reminder_set",
            "description": "Set a reminder with specified text and optional delay in seconds.",
            "parameters": {
                "type": "object",
                "properties": {
                    "text": {
                        "type": "string",
                        "description": "Reminder message.",
                    },
                    "seconds": {
                        "type": "number",
                        "description": "Seconds until reminder triggers.",
                    },
                },
                "required": ["text"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "note_append",
            "description": "Save a quick text note to disk.",
            "parameters": {
                "type": "object",
                "properties": {
                    "text": {
                        "type": "string",
                        "description": "Note content to save.",
                    }
                },
                "required": ["text"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "keyboard_type",
            "description": "Type text into the currently active window or input form box.",
            "parameters": {
                "type": "object",
                "properties": {
                    "text": {
                        "type": "string",
                        "description": "Text to type into active input field.",
                    }
                },
                "required": ["text"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "keyboard_press",
            "description": "Press a virtual key in the active window (e.g. 'enter', 'tab', 'escape', 'space').",
            "parameters": {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "string",
                        "enum": [
                            "enter",
                            "return",
                            "tab",
                            "space",
                            "escape",
                            "esc",
                            "backspace",
                            "delete",
                            "up",
                            "down",
                            "left",
                            "right",
                            "home",
                            "end",
                            "pageup",
                            "pagedown",
                        ],
                        "description": "Key name to press.",
                    }
                },
                "required": ["key"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "conversation_reply",
            "description": "Reply conversationally to the user when no system action is required.",
            "parameters": {
                "type": "object",
                "properties": {
                    "reply": {
                        "type": "string",
                        "description": "Conversational spoken reply to the user.",
                    }
                },
                "required": ["reply"],
            },
        },
    },
]


def get_openai_tools() -> list[dict[str, Any]]:
    """Return tool declarations for OpenAI-compatible APIs (Agnes, Ollama)."""
    return NOVA_TOOLS_SCHEMA


def get_gemini_function_declarations(non_blocking: bool = False) -> list[Any]:
    """Generate google.genai.types.FunctionDeclaration list for Gemini."""
    try:
        from google.genai import types

        decls: list[Any] = []
        for item in NOVA_TOOLS_SCHEMA:
            fn = item["function"]
            kwargs: dict[str, Any] = {
                "name": fn["name"],
                "description": fn["description"],
                "parameters": fn.get("parameters"),
            }
            if non_blocking:
                kwargs["behavior"] = "NON_BLOCKING"
            decls.append(types.FunctionDeclaration(**kwargs))
        return decls
    except Exception as e:
        logger.debug("Failed to create Google GenAI FunctionDeclarations: %s", e)
        return []


def parse_tool_call(
    name: str, arguments: dict[str, Any], raw_query: str = ""
) -> ActionRequest | None:
    """Parse an LLM tool call into a strictly validated ActionRequest.

    Returns None if the tool call fails allowlist validation.
    """
    try:
        clean_name = name.strip()

        if clean_name == "volume_set":
            percent = int(arguments.get("percent", 50))
            req = ActionRequest(
                action_id=ActionID.VOLUME_SET.value,
                parameters={"percent": percent},
                feedback_phrase=f"Setting volume to {percent} percent.",
                raw_query=raw_query,
            )
        elif clean_name == "volume_change":
            direction = str(arguments.get("direction", "up")).lower()
            if direction == "up":
                req = ActionRequest(
                    action_id=ActionID.VOLUME_UP.value,
                    feedback_phrase="Increasing volume.",
                    raw_query=raw_query,
                )
            else:
                req = ActionRequest(
                    action_id=ActionID.VOLUME_DOWN.value,
                    feedback_phrase="Decreasing volume.",
                    raw_query=raw_query,
                )
        elif clean_name == "volume_mute_toggle":
            req = ActionRequest(
                action_id=ActionID.VOLUME_MUTE_TOGGLE.value,
                feedback_phrase="Toggling mute.",
                raw_query=raw_query,
            )
        elif clean_name == "media_control":
            act = str(arguments.get("action", "play_pause")).lower()
            if act == "next":
                aid = ActionID.MEDIA_NEXT.value
                feedback = "Playing next track."
            elif act == "previous":
                aid = ActionID.MEDIA_PREVIOUS.value
                feedback = "Playing previous track."
            elif act == "stop":
                aid = ActionID.MEDIA_STOP.value
                feedback = "Stopping media playback."
            else:
                aid = ActionID.MEDIA_PLAY_PAUSE.value
                feedback = "Toggling media playback."
            req = ActionRequest(
                action_id=aid,
                feedback_phrase=feedback,
                raw_query=raw_query,
            )
        elif clean_name == "app_launch":
            app_name = str(arguments.get("app_name", "")).strip()
            req = ActionRequest(
                action_id=ActionID.APP_LAUNCH.value,
                parameters={"app_name": app_name},
                feedback_phrase=f"Launching {app_name}.",
                raw_query=raw_query,
            )
        elif clean_name == "app_close":
            app_name = str(arguments.get("app_name", "")).strip()
            req = ActionRequest(
                action_id=ActionID.APP_CLOSE.value,
                parameters={"app_name": app_name},
                feedback_phrase=f"Closing {app_name}.",
                raw_query=raw_query,
                is_destructive=True,
            )
        elif clean_name == "system_lock":
            req = ActionRequest(
                action_id=ActionID.SYSTEM_LOCK.value,
                feedback_phrase="Locking workstation.",
                raw_query=raw_query,
                is_destructive=True,
            )
        elif clean_name == "system_sleep":
            req = ActionRequest(
                action_id=ActionID.SYSTEM_SLEEP.value,
                feedback_phrase="Putting system to sleep.",
                raw_query=raw_query,
                is_destructive=True,
            )
        elif clean_name == "dark_mode_toggle":
            req = ActionRequest(
                action_id=ActionID.DARK_MODE_TOGGLE.value,
                feedback_phrase="Toggling dark mode.",
                raw_query=raw_query,
            )
        elif clean_name == "web_search":
            query = str(arguments.get("query", "")).strip()
            req = ActionRequest(
                action_id=ActionID.WEB_SEARCH.value,
                parameters={"query": query},
                feedback_phrase=f"Searching for {query}.",
                raw_query=raw_query,
            )
        elif clean_name == "web_open_url":
            url = str(arguments.get("url", "")).strip()
            if not (url.startswith("http://") or url.startswith("https://")):
                url = f"https://{url}"
            req = ActionRequest(
                action_id=ActionID.WEB_OPEN_URL.value,
                parameters={"url": url},
                feedback_phrase=f"Opening {url}.",
                raw_query=raw_query,
            )
        elif clean_name == "timer_set":
            duration = float(arguments.get("duration_seconds", 60.0))
            req = ActionRequest(
                action_id=ActionID.TIMER_SET.value,
                parameters={"duration_seconds": duration},
                feedback_phrase=f"Setting timer for {int(duration)} seconds.",
                raw_query=raw_query,
            )
        elif clean_name == "reminder_set":
            text = str(arguments.get("text", "")).strip()
            secs = float(arguments.get("seconds", 0.0))
            req = ActionRequest(
                action_id=ActionID.REMINDER_SET.value,
                parameters={"text": text, "seconds": secs},
                feedback_phrase=f"Setting reminder: {text}.",
                raw_query=raw_query,
            )
        elif clean_name == "note_append":
            text = str(arguments.get("text", "")).strip()
            req = ActionRequest(
                action_id=ActionID.NOTE_APPEND.value,
                parameters={"text": text},
                feedback_phrase="Note saved.",
                raw_query=raw_query,
            )
        elif clean_name == "keyboard_type":
            text = str(arguments.get("text", ""))
            req = ActionRequest(
                action_id=ActionID.KEYBOARD_TYPE.value,
                parameters={"text": text},
                feedback_phrase="Typing text.",
                raw_query=raw_query,
            )
        elif clean_name == "keyboard_press":
            key = str(arguments.get("key", "")).strip().lower()
            req = ActionRequest(
                action_id=ActionID.KEYBOARD_PRESS.value,
                parameters={"key": key},
                feedback_phrase=f"Pressing {key}.",
                raw_query=raw_query,
            )
        elif clean_name == "conversation_reply":
            reply = str(arguments.get("reply", "")).strip()
            req = ActionRequest(
                action_id=ActionID.CONVERSATION_REPLY.value,
                parameters={"reply": reply},
                feedback_phrase=reply,
                raw_query=raw_query,
            )
        else:
            logger.warning("Unrecognized tool name from LLM: %s", clean_name)
            return None

        # Strictly validate against Rule R5 allowlist
        AllowlistValidator.validate(req)
        return req
    except Exception as e:
        logger.warning("Failed to parse or validate tool call '%s': %s", name, e)
        return None
