"""Typed interfaces and data models for NOVA core subsystems.

All interfaces use typing.Protocol to enable structural subtyping and clean
decoupling between core orchestration and concrete platform/engine implementations.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol, runtime_checkable

import numpy as np


@dataclass(frozen=True)
class TranscriptionResult:
    """Result of speech-to-text recognition."""

    text: str
    confidence: float = 1.0
    language: str = "en"
    duration_seconds: float = 0.0


@dataclass(frozen=True)
class ActionRequest:
    """Structured, allowlisted action request generated by an intent engine."""

    action_id: str
    parameters: dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    is_destructive: bool = False
    feedback_phrase: str = ""
    raw_query: str = ""


@dataclass(frozen=True)
class ActionResult:
    """Result of executing a platform or skill action."""

    success: bool
    message: str
    data: dict[str, Any] = field(default_factory=dict)
    error: str | None = None


@runtime_checkable
class STTEngineProtocol(Protocol):
    """Protocol for Speech-to-Text inference engines."""

    def transcribe(self, audio_data: np.ndarray[Any, Any]) -> TranscriptionResult:
        """Transcribe a 16kHz float32 mono audio NumPy array into text."""
        ...

    def is_available(self) -> bool:
        """Return True if the model weights are loaded and ready."""
        ...


@runtime_checkable
class IntentEngineProtocol(Protocol):
    """Protocol for intent classification and slot-filling engines."""

    def resolve_intent(self, text: str) -> ActionRequest | None:
        """Parse natural language into a validated, allowlisted ActionRequest."""
        ...


@runtime_checkable
class TTSEngineProtocol(Protocol):
    """Protocol for Text-to-Speech synthesis engines."""

    def synthesize(self, text: str, voice: str | None = None) -> bytes:
        """Synthesize text into raw WAV/PCM audio bytes."""
        ...

    def stop(self) -> None:
        """Immediately abort any active speech synthesis and playback."""
        ...


@runtime_checkable
class PlatformAdapterProtocol(Protocol):
    """Protocol for operating system interactions (Windows/Linux)."""

    def set_volume(self, percent: int) -> ActionResult:
        """Set master volume between 0 and 100."""
        ...

    def get_volume(self) -> int:
        """Get current master volume between 0 and 100."""
        ...

    def toggle_mute(self) -> ActionResult:
        """Toggle audio mute state."""
        ...

    def media_play_pause(self) -> ActionResult:
        """Toggle media playback (play/pause)."""
        ...

    def media_next(self) -> ActionResult:
        """Skip to next media track."""
        ...

    def media_previous(self) -> ActionResult:
        """Return to previous media track."""
        ...

    def lock_workstation(self) -> ActionResult:
        """Lock the operating system user session."""
        ...

    def suspend_system(self) -> ActionResult:
        """Put the computer into suspend / sleep mode."""
        ...

    def launch_app(self, app_name_or_target: str) -> ActionResult:
        """Launch an allowlisted application by registered name or alias."""
        ...

    def close_app(self, app_name_or_target: str) -> ActionResult:
        """Gracefully close a running application."""
        ...

    def toggle_dark_mode(self) -> ActionResult:
        """Toggle between OS dark and light themes."""
        ...

    def open_url(self, url: str) -> ActionResult:
        """Open a validated URL in the user's default web browser."""
        ...


@runtime_checkable
class ConfirmationHandlerProtocol(Protocol):
    """Protocol for requesting user confirmation for destructive actions."""

    def request_confirmation(self, action: ActionRequest) -> bool:
        """Prompt user via voice or modal dialog. Return True if approved."""
        ...
